#!/bin/bash
#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app       = $YNH_APP_INSTANCE_NAME

path_url  = $(ynh_app_setting_get $app path)
final_path= $(ynh_app_setting_get $app final_path)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_backup_before_upgrade
ynh_clean_setup () {
    ynh_restore_upgradebackup
}
ynh_abort_if_errors

#=================================================
# ADD FILES TO BACKUP
#=================================================

#save database and config before replace all files
sudo -i -u postgres
pg_dumpall > noalyss_backup.dmp
ynh_backup 'noalyss_backup.dmp' 'conf/noalyss_backup.dmp'
ynh_backup $final_path '/include/config.inc.php' 'etc/tmp/'

#Import new files
sudo cp -a ../sources/html/ $final_path
sudo cp -a ../sources/include/ $final_path

#Restore files config
ynh_restore_file 'noalyss/include/config.inc.php'
#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
